stages:
  - install
  - quality
  - build
  - pages

variables:
  PNPM_STORE_PATH: .pnpm-store
  HUSKY: '0'

default:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_PATH

# Установка зависимостей
install:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/
      - .pnpm-store
    expire_in: 1 hour # Чтобы не занимать место надолго
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - $PNPM_STORE_PATH
    policy: pull-push

# Проверка качества кода
prettier:
  stage: quality
  script:
    - pnpm run prettier:check
  dependencies:
    - install

eslint:
  stage: quality
  script:
    - pnpm run lint:check
  dependencies:
    - install

test:
  stage: quality
  script:
    - pnpm run test
  dependencies:
    - install

types:
  stage: quality
  script:
    - pnpm run types:check
  dependencies:
    - install

build:
  stage: build
  script:
    - pnpm run build
  dependencies:
    - install
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

pages:
  stage: pages
  script:
    - mkdir -p public
    - cp -r dist/* public/
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - develop
